### ISSUE TITLE
error on running test server 

### ISSUE THREAD

**Issue by metapraveen** [lcjnil/react-redux-scaffold#10]
![screenshot 2016-01-13 02 12 50](https://cloud.githubusercontent.com/assets/2039089/12276464/ec173184-b99b-11e5-9624-ccdf8e112089.png)

**Comment by lcjnil** [comment]
Please check your .eslintrc, you can custom your own lint options.
However, I could't reproduce it with default settings.
Due to dependencies have been updated greatly, I'll update this scaffold in few days.

**Comment by metapraveen** [comment]
Thanks for the reply. I will check and close this issue
