### ISSUE TITLE
No gulpfile found error

### ISSUE THREAD

**Issue by Gnex77** [lcjnil/react-redux-scaffold#2]
when I run `gulp serve` I get a `No gulpfile found` error. I see the gulpfile.babel.js is there something I need to start or run before that file can be recognized as a gulpfile?

**Comment by lcjnil** [comment]
Have you installed all the dependencies? If so,  `gulp serve` could work.

**Comment by Gnex77** [comment]
I ran `npm install` from inside the app directory, but I still get the no gulpfile error.

**Comment by Gnex77** [comment]
Closing issue. I had an older version of gulp install globally and that is why it was not finding the `gulpfile.babel.js` file. Thanks.
