### ISSUE TITLE
Please integrate babel-plugin-react-transform with error handling

### ISSUE THREAD

**Issue by JiLiZART** [lcjnil/react-redux-scaffold#3]
Thanks for very useful boilerplate. Not long ago Dan Abramov released very useful https://github.com/gaearon/react-transform-boilerplate tasty boilerplate, demonstrating live reload and error handling.

**Comment by lcjnil** [comment]
Thx for your message, I am on my vacation and I will try it later

**Comment by lcjnil** [comment]
@JiLiZART Hello, I want to know why you want to integrate this babel plugin. Current I am using react-hot-loader, and I think it's good enough.

**Comment by lcjnil** [comment]
Used that in latest code, @JiLiZART thanks for your message
