### ISSUE TITLE
Update scaffold when release react 0.14

### ISSUE THREAD

**Issue by lcjnil** [lcjnil/react-redux-scaffold#4]
- [x] update react 
- [x] update redux
- [x] update react-router and try using [redux-router](https://github.com/rackt/redux-router.git)
- [x] remove gulp
- [x] better index generate
- [x] new doc

**Comment by Droid-Kree** [comment]
Looks like React 0.14 released!

**Comment by lcjnil** [comment]
@Droid-Kree thx, I add some todos now
