### ISSUE TITLE
build task aint copying index.html

### ISSUE THREAD

**Issue by sap9433** [lcjnil/react-redux-scaffold#5]
Build task is not copying index.html in dis folder . Without index.html how the app will work ?

**Comment by lcjnil** [comment]
Yes, this is a bug, I just cp src/index.html dist/, and edit to get things work. I'll try to fix it by using some templates.

**Comment by lcjnil** [comment]
@sap9433 Hi, I had handled this issues via 42b30082098a412cb3dc2b64333e27f64b259bca, use `html-webpack-plugin`.
I had checked your PR, and it cant handle path change( I mean, when build production, the url to main.js is quite different from development, and may use hashes)
Current, it's a ugly patch, and I will do more in few days.

**Comment by lcjnil** [comment]
@sap9433 please try latest code, it fixed this issue totally.
